# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sunnytui < Formula
  desc "TUI multiplexor de Claude Code"
  homepage "https://github.com/noesrafa/sunnytui"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.3/sunnytui_0.8.3_darwin_amd64.tar.gz"
      sha256 "bca4367b2fee68edb40e6b70c6832cf4ddbe95c7b3cfd123ac0a6afb49841cdc"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.3/sunnytui_0.8.3_darwin_arm64.tar.gz"
      sha256 "49eeb5462f77946c7d562c0cd6a8f62c920a611eb677aa0c23c9bfda79871f1d"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.3/sunnytui_0.8.3_linux_amd64.tar.gz"
      sha256 "12633d076bafa18fefe83fe8f483e16df06065511c44dd8c12b0455c177008dd"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.3/sunnytui_0.8.3_linux_arm64.tar.gz"
      sha256 "34777027f63ebe172f83413f89bbddd5098cc623592ed33e87985e6de00db8ec"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  test do
    system "#{bin}/sunnytui", "--help"
    system "#{bin}/sunny", "--help"
  end
end
