# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sunnytui < Formula
  desc "TUI multiplexor de Claude Code"
  homepage "https://github.com/noesrafa/sunnytui"
  version "0.13.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.13.6/sunnytui_0.13.6_darwin_amd64.tar.gz"
      sha256 "b9b1652945fc99baddc6fa37c7c27152b21f0e8a007050b713f9bd7411d987a2"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.13.6/sunnytui_0.13.6_darwin_arm64.tar.gz"
      sha256 "0ef8b64dc311e70c6c702f7f5baa4dd43b51c5a3d5193d8a93cf4448df635df6"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.13.6/sunnytui_0.13.6_linux_amd64.tar.gz"
      sha256 "2d52139a2d06e282e48cdc2b44e3f9697d407a158695dd478ed4fa349949a9f0"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.13.6/sunnytui_0.13.6_linux_arm64.tar.gz"
      sha256 "c2d0619087b0d3587c9966c3ea3f224cf169c86a7c16bf2a0ee2a2c579a62e58"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  test do
    system "#{bin}/sunnytui", "--help"
    system "#{bin}/sunny", "--help"
  end
end
