# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sunnytui < Formula
  desc "TUI multiplexor de Claude Code"
  homepage "https://github.com/noesrafa/sunnytui"
  version "0.8.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.5/sunnytui_0.8.5_darwin_amd64.tar.gz"
      sha256 "95d8ca53148583012c81663f47a07653e176959d901710280cf5167c71ac569f"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.5/sunnytui_0.8.5_darwin_arm64.tar.gz"
      sha256 "83c1ef7b6623936f7725565942d89734d8cb3ff88f26710c697f3ddba107c50c"

      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.5/sunnytui_0.8.5_linux_amd64.tar.gz"
      sha256 "644bb3ca8fb1e4f212e8c51b1c46d1a1faa8a1f54ce0ba8e0b713f6a214a6a6b"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunnytui/releases/download/v0.8.5/sunnytui_0.8.5_linux_arm64.tar.gz"
      sha256 "48fe763d6dcac78d590ad66c9d262bb58a425ab7f6543f25183b2857c1afdbdb"
      define_method(:install) do
        bin.install "sunnytui"
        # Symlink so users can launch via the short `sunny` name.
        bin.install_symlink "sunnytui" => "sunny"
      end
    end
  end

  test do
    system "#{bin}/sunnytui", "--help"
    system "#{bin}/sunny", "--help"
  end
end
