# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sunny < Formula
  desc "Self-hosted personal agent. One binary, your data, your rules."
  homepage "https://github.com/noesrafa/sunny"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noesrafa/sunny/releases/download/v0.10.1/sunny_0.10.1_darwin_arm64.tar.gz"
      sha256 "17a47a46ff2ee22bb7b7cd26378ffdf59522db0efa39c70a0cbf60e1ca7613af"

      define_method(:install) do
        bin.install "sunny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noesrafa/sunny/releases/download/v0.10.1/sunny_0.10.1_linux_amd64.tar.gz"
      sha256 "c06e082c3fa6f40a0634f6cbbcdbb9131cd8469283250a23c22451e03b62bcb3"
      define_method(:install) do
        bin.install "sunny"
      end
    end
  end

  test do
    system "#{bin}/sunny", "version"
  end
end
